# Offensive Scoring Categories
_TOUCHDOWN_RUSHING = "TOUCHDOWN_RUSHING"
_TOUCHDOWN_RECEIVING = "TOUCHDOWN_RECEIVING"
_TOUCHDOWN_THROWING = "TOUCHDOWN_THROWING"
_TOUCHDOWN_RETURN = "TOUCHDOWN_RETURN"
_YARDS_RUSHING = "YARDS_RUSHING"
_YARDS_RECEIVING = "YARDS_RECEIVING"
_YARDS_THROWING = "YARDS_THROWING"
_YARDS_RETURN = "YARDS_RETURN"
_RECEPTION = "RECEPTION"
_INTERCEPTION_THROW = "INTERCEPTION_THROW"
_TWO_POINT_CONVERSION = "TWO_POINT_CONVERSION"
_FUMBLE_LOST = "FUMBLE_LOST"
_TOUCHDOWN_FUMBLE_RECOVERY = "TOUCHDOWN_FUMBLE_RECOVERY"
# Kicking Scoring Categories
_FIELD_GOAL_0_39_YDS = "_FIELD_GOAL_0_39_YDS"
_FIELD_GOAL_40_49_YDS = "_FIELD_GOAL_40_49_YDS"
_FIELD_GOAL_50_OR_MORE_YDS = "_FIELD_GOAL_50_OR_MORE_YDS"
_MADE_PAT = "_MADE_PAT"
# Defense Scoring Categories
_SACK = "SACK"
_INTERCEPTION = "INTERCEPTION"
_FUMBLE_RECOVERY = "FUMBLE_RECOVERY"
_TOUCHDOWN_DEFENSE = "TOUCHDOWN_DEFENSE"
_SAFETY = "SAFETY"
_BLOCK_KICK = "BLOCK_KICK"
_EXTRA_POINT_RETURN = "EXTRA_POINT_RETURN"
_POINTS_ALLOWED_0 = "POINTS_ALLOWED_0"
_POINTS_ALLOWED_1_6 = "POINTS_ALLOWED_1_6"
_POINTS_ALLOWED_7_13 = "POINTS_ALLOWED_7_13"
_POINTS_ALLOWED_14_20 = "POINTS_ALLOWED_14_20"
_POINTS_ALLOWED_21_27 = "POINTS_ALLOWED_21_28"
_POINTS_ALLOWED_28_34 = "POINTS_ALLOWED_28_34"
_POINTS_ALLOWED_35_OR_MORE = "POINTS_ALLOWED_35_OR_MORE"

# The scoring values for each category.
_SCORING_VALUES = {
    _TOUCHDOWN_RUSHING: 6,
    _TOUCHDOWN_RECEIVING: 6,
    _TOUCHDOWN_THROWING: 4,
    _TOUCHDOWN_RETURN: 6,
    _YARDS_RUSHING: .1,
    _YARDS_RECEIVING: .1,
    _YARDS_THROWING: .04,
    _YARDS_RETURN: .04,
    _RECEPTION: .5,
    _INTERCEPTION_THROW: -1.5,
    _TWO_POINT_CONVERSION: 2,
    _FUMBLE_LOST: -2,
    _TOUCHDOWN_FUMBLE_RECOVERY: 6,
    _FIELD_GOAL_0_39_YDS: 3,
    _FIELD_GOAL_40_49_YDS: 4,
    _FIELD_GOAL_50_OR_MORE_YDS: 5,
    _MADE_PAT: 1,
    _SACK: 1,
    _INTERCEPTION: 2,
    _FUMBLE_RECOVERY: 2,
    _TOUCHDOWN_DEFENSE: 6,
    _BLOCK_KICK: 2,
    _EXTRA_POINT_RETURN: 2,
    _POINTS_ALLOWED_0: 10,
    _POINTS_ALLOWED_1_6: 7,
    _POINTS_ALLOWED_7_13: 4,
    _POINTS_ALLOWED_14_20: 1,
    _POINTS_ALLOWED_21_27: 0,
    _POINTS_ALLOWED_28_34: -1,
    _POINTS_ALLOWED_35_OR_MORE: -4,
}


