import pandas as pd
import os
import base64
from io import BytesIO
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set_theme(style="whitegrid")

def generate_html_report(week, season, output_dir):
    print(f"Generating HTML report for Season {season} Week {week}...")
    
    # Load the summary CSV
    summary_path = os.path.join(output_dir, "summary.csv")
    if not os.path.exists(summary_path):
        print("Summary CSV not found.")
        return

    df = pd.read_csv(summary_path)
    
    # Create HTML content
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Fantasy Projections {season} Week {week}</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f7; color: #333; }}
            .container {{ max_width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            h1 {{ text-align: center; color: #1d1d1f; }}
            h2 {{ border-bottom: 2px solid #f5f5f7; padding-bottom: 10px; margin-top: 40px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }}
            th, td {{ text-align: left; padding: 12px; border-bottom: 1px solid #eee; }}
            th {{ background-color: #f5f5f7; font-weight: 600; }}
            tr:hover {{ background-color: #fbfbfb; }}
            .tier-starter {{ color: #2e7d32; font-weight: bold; }}
            .tier-fringe {{ color: #f57f17; }}
            .tier-bench {{ color: #757575; }}
            .boom-high {{ color: #d32f2f; font-weight: bold; }} /* High upside */
            .img-container {{ text-align: center; margin: 40px 0; }}
            img {{ max-width: 100%; height: auto; border-radius: 8px; }}
            .meta {{ font-size: 12px; color: #888; text-align: center; margin-top: 40px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🏈 Fantasy Projections: Week {week}, {season}</h1>
            
            <div class="img-container">
                <h3>Top 30 Flex Projections (PPR Range)</h3>
                {generate_box_plot(df)}
            </div>

            {generate_position_section(df, "QB", 16)}
            {generate_position_section(df, "RB", 30)}
            {generate_position_section(df, "WR", 36)}
            {generate_position_section(df, "TE", 14)}
            {generate_position_section(df, "K", 12)}
            {generate_position_section(df, "DEF", 12)}

            <div class="meta">
                Generated by FantasyFootballProjections Engine v410+
            </div>
        </div>
    </body>
    </html>
    """
    
    output_path = os.path.join(output_dir, "report.html")
    with open(output_path, "w") as f:
        f.write(html_content)
    print(f"Report saved to: {output_path}")

def generate_box_plot(df):
    # Filter Flex positions
    flex = df.loc[df.position.isin(['RB', 'WR', 'TE'])].copy()
    flex = flex.sort_values('median', ascending=False).head(30)
    flex = flex.reset_index(drop=True)
    
    fig, ax = plt.subplots(figsize=(10, 12))
    
    y = range(len(flex))
    # Invert Y so top player is at top
    y = [len(flex) - 1 - i for i in y]
    
    # 1. Range Line (p12 - p88) - The "Tail"
    ax.hlines(y, flex['percentile_12'], flex['percentile_88'], color='#e0e0e0', linewidth=2, zorder=1)
    
    # 2. Likely Range (p25 - p75) - The "Body"
    pos_colors = {'RB': '#1976D2', 'WR': '#388E3C', 'TE': '#FBC02D'}
    colors = [pos_colors.get(p, '#333') for p in flex['position']]
    
    ax.hlines(y, flex['percentile_25'], flex['percentile_75'], colors=colors, linewidth=6, zorder=2)
    
    # 3. Median Dot
    ax.scatter(flex['median'], y, color='white', edgecolor=colors, s=60, linewidth=2, zorder=3)
    
    # 4. Labels
    for i, (idx, row) in enumerate(flex.iterrows()):
        y_pos = len(flex) - 1 - i
        label = f"{row['player_name']} {row['position']}"
        ax.text(row['percentile_12'] - 0.5, y_pos, label, va='center', ha='right', fontsize=10, color='#333')
        
        # Annotate Median
        ax.text(row['median'], y_pos + 0.3, f"{row['median']:.1f}", va='bottom', ha='center', fontsize=8, color=colors[i], fontweight='bold')

    ax.set_yticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_color('#ddd')
    
    ax.set_xlabel("Projected Points (0.5 PPR)", fontsize=12, color='#555')
    ax.tick_params(axis='x', colors='#555')
    ax.grid(axis='x', linestyle=':', alpha=0.5)
    
    plt.title("Week Projections: Likely Outcomes (Range represents 12th-88th percentile)", loc='left', fontsize=16, pad=20)
    plt.tight_layout()
    
    # Save
    buf = BytesIO()
    plt.savefig(buf, format='png', dpi=100, bbox_inches='tight')
    plt.close()
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return f'<img src="data:image/png;base64,{data}"/>'

def generate_position_section(df, pos, top_n):
    subset = df.loc[df.position == pos].sort_values('median', ascending=False).head(top_n)
    
    rows = ""
    for _, row in subset.iterrows():
        # Determine Tier
        rank = _ + 1 # Index doesn't reset automatically in loop unless we reset
        # Actually _ is the index from original df. We need loop counter.
        pass 
        
    # Fix iteration
    subset = subset.reset_index(drop=True)
    for idx, row in subset.iterrows():
        rank = idx + 1
        tier_class = "tier-bench"
        if rank <= 12: tier_class = "tier-starter"
        elif rank <= 24: tier_class = "tier-fringe"
        
        # Boom Rating: Difference between p88 and median
        upside = row['percentile_88'] - row['median']
        upside_str = f"+{upside:.1f}"
        if upside > 10: upside_str = f'<span class="boom-high">{upside_str} 🚀</span>'
        
        rows += f"""
        <tr>
            <td>{rank}</td>
            <td class="{tier_class}">{row['player_name']}</td>
            <td>{row['team']}</td>
            <td>{row['median']:.1f}</td>
            <td>{row['percentile_25']:.1f} - {row['percentile_75']:.1f}</td>
            <td>{row['percentile_88']:.1f} ({upside_str})</td>
        </tr>
        """
        
    return f"""
    <h2>{pos} Rankings</h2>
    <table>
        <thead>
            <tr>
                <th width="50">Rank</th>
                <th>Player</th>
                <th>Team</th>
                <th>Median</th>
                <th>Likely Range (25-75%)</th>
                <th>Ceiling (88%)</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    """
